// Status Enums from Prisma schema

export enum AgendaItemStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  VETTED = "VETTED",
  APPROVED_FOR_AGENDA = "APPROVED_FOR_AGENDA",
  CIRCULATED = "CIRCULATED",
  DECIDED = "DECIDED",
  CLOSED = "CLOSED",
  RETURNED = "RETURNED",
  DEFERRED = "DEFERRED",
  WITHDRAWN = "WITHDRAWN",
}

export enum WorkingPaperStatus {
  INSTANTIATED = "INSTANTIATED",
  IN_AUTHORING = "IN_AUTHORING",
  IN_REVIEW = "IN_REVIEW",
  FINALIZED = "FINALIZED",
  CIRCULATED = "CIRCULATED",
  ARCHIVED = "ARCHIVED",
}

export enum ActionTakenEntryStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  BLOCKED = "BLOCKED",
  CLOSED = "CLOSED",
}

export enum UserRole {
  AUTHORIZED_PROPOSER = "AUTHORIZED_PROPOSER",
  FEEDER_BODY_SECRETARY = "FEEDER_BODY_SECRETARY",
  REGISTRAR = "REGISTRAR",
  TREASURER_LEGAL = "TREASURER_LEGAL",
  VICE_CHANCELLOR = "VICE_CHANCELLOR",
  SYNDICATE_MEMBER = "SYNDICATE_MEMBER",
  SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR",
}
