// Status Enums from Prisma schema

export enum AgendaItemStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  VETTED = "VETTED",
  APPROVED_FOR_AGENDA = "APPROVED_FOR_AGENDA",
  CIRCULATED = "CIRCULATED",
  DECIDED = "DECIDED",
  CLOSED = "CLOSED",
  RETURNED = "RETURNED",
  DEFERRED = "DEFERRED",
  WITHDRAWN = "WITHDRAWN",
}

export enum WorkingPaperStatus {
  INSTANTIATED = "INSTANTIATED",
  IN_AUTHORING = "IN_AUTHORING",
  IN_REVIEW = "IN_REVIEW",
  FINALIZED = "FINALIZED",
  CIRCULATED = "CIRCULATED",
  ARCHIVED = "ARCHIVED",
}

export enum ActionTakenEntryStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  BLOCKED = "BLOCKED",
  CLOSED = "CLOSED",
}

export enum UserRole {
  AUTHORIZED_PROPOSER = "AUTHORIZED_PROPOSER",
  FEEDER_BODY_SECRETARY = "FEEDER_BODY_SECRETARY",
  REGISTRAR = "REGISTRAR",
  TREASURER_LEGAL = "TREASURER_LEGAL",
  VICE_CHANCELLOR = "VICE_CHANCELLOR",
  SYNDICATE_MEMBER = "SYNDICATE_MEMBER",
  SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR",
}

export enum ASRBCaseStatus {
  RECEIVED = "RECEIVED",
  COMPLIANCE_EVALUATED = "COMPLIANCE_EVALUATED",
  VETTING = "VETTING",
  READY_FOR_AGENDA = "READY_FOR_AGENDA",
  ON_AGENDA = "ON_AGENDA",
  DECIDED = "DECIDED",
  CLOSED = "CLOSED",
  RETURNED = "RETURNED",
  HELD = "HELD",
  WITHDRAWN = "WITHDRAWN",
  URGENT_CIRCULATION = "URGENT_CIRCULATION",
  DEFERRED = "DEFERRED",
}

export enum CaseType {
  SYNOPSIS_APPROVAL = "SYNOPSIS_APPROVAL",
  GEC_CONSTITUTION = "GEC_CONSTITUTION",
  EXAMINER_APPOINTMENT = "EXAMINER_APPOINTMENT",
  RESULT_APPROVAL = "RESULT_APPROVAL",
  SUPERVISOR_CHANGE = "SUPERVISOR_CHANGE",
  TOPIC_CHANGE = "TOPIC_CHANGE",
  EXTENSION_CANDIDATURE = "EXTENSION_CANDIDATURE",
  LEAVE_ABSENCE = "LEAVE_ABSENCE",
  RESEARCH_PROJECT_APPROVAL = "RESEARCH_PROJECT_APPROVAL",
  COMPREHENSIVE_RESULT = "COMPREHENSIVE_RESULT",
  COURSEWORK_WAIVER = "COURSEWORK_WAIVER",
  OTHER = "OTHER",
}

export enum CaseUrgency {
  NORMAL = "NORMAL",
  URGENT_CIRCULATION = "URGENT_CIRCULATION",
}

export enum FeederBodyType {
  DGSC = "DGSC",
  FACULTY_BOARD = "FACULTY_BOARD",
}

export enum RuleSource {
  HEC = "HEC",
  UNIVERSITY = "UNIVERSITY",
  FACULTY = "FACULTY",
  PROGRAMME = "PROGRAMME",
}

export enum RuleSeverity {
  BLOCKING = "BLOCKING",
  WARNING = "WARNING",
  INFORMATIONAL = "INFORMATIONAL",
}

export enum RuleOutcome {
  PASS = "PASS",
  FAIL = "FAIL",
  WARN = "WARN",
  NOT_APPLICABLE = "NOT_APPLICABLE",
  ERROR = "ERROR",
}

export enum ComplianceStatus {
  COMPLIANT = "COMPLIANT",
  NEEDS_REVIEW = "NEEDS_REVIEW",
  NON_COMPLIANT = "NON_COMPLIANT",
}
